default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username
      password: password
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: p-project-sucide-helpline_development

test:
  <<: *default
  database: p-project-sucide-helpline_test

production:
  <<: *default
  database: p-project-sucide-helpline_production